* Dante: Emacs mode for Interactive Haskell

  #+ATTR_HTML: title="Join the chat at https://gitter.im/dante-mode/Lobby"
  [[https://gitter.im/dante-mode/Lobby?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge][file:https://badges.gitter.im/dante-mode/Lobby.svg]]

[[http://stable.melpa.org/packages/dante-badge.svg]]

Dante is a fork of Intero mode. It steals many good ideas from Intero,
it aims for light weightedness. Dante has no dependency on "Stack" nor
on any custom Haskell code. Dante's Emacs code is about half as long
as that of Intero. Flychecking is optional (yet recommended).

** Features

| Feature                                 | How to use                   |
|-----------------------------------------+------------------------------|
| Flycheck type checking                  | enable flycheck-mode         |
| Type of selection                       | C-c C-t                      |
| Info at point                           | C-c C-i                      |
| Apply Ghc suggestion for error at point | C-c C-a                      |
| Goto definition                         | (xref-find-definitions)      |
| Find uses                               | (xref-find-references)       |
| REPLoid (*)                             | C-c C-e at {-> expression -} |

(*) REPLoid explanation: 

#+BEGIN_SRC Haskell
example :: [String]
example = ["This is an example", "of", "interactive", "evaluation"]

{-> intercalate " " example

-}
#+END_SRC
In the above file, if you type ~C-c C-e~ on the line containing
"intercalate", you'll get:

#+BEGIN_SRC haskell
{-> intercalate " " example

"This is an example of interactive evaluation"
-}
#+END_SRC

** Installation

Turn on Dante in your ~haskell-mode-hook~. I recommend:

#+BEGIN_SRC elisp
  (use-package dante
    :ensure t
    :commands 'dante-mode
    :init
    (add-hook 'haskell-mode-hook 'dante-mode)
    (add-hook 'haskell-mode-hook 'flycheck-mode))
#+END_SRC

You may want to be sure not to enable ~(interactive-haskell-mode)~ so
that Dante keybindings are not hidden.

** Customization

M-x customize-group dante
